### ISSUE TITLE
volare enable remotedisconnected

### ISSUE THREAD

**Issue by yihuajack** [efabless/volare#26]
I was running `make` of OpenLane in WSL 2 with all prerequisites satisfied including Docker. When it ran `./venv/bin/volare enable` after creating a venv and upgrading volare in the venv, it seemed to wait for a few seconds and showed:
> [10:09:34] Found version de752ec0ba4da0ecb1fbcd309eeec4993d88f5bc in ./dependencies/tool_metadata.yml.     common.py:226
Traceback (most recent call last):
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
  File "/mnt/d/Resources/OpenLane/./venv/bin/volare", line 8, in <module>
    sys.exit(cli())
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/volare/manage.py", line 320, in enable_cmd
    enable(pdk_root=pdk_root, pdk=pdk, version=version)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/volare/manage.py", line 240, in enable
    with requests.get(link, stream=True) as r:
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/d/Resources/OpenLane/venv/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

I tried to run the command in `bash` but it gives the same error. The connection to GitHub is proved to be of no problem. Are there any ways to know what happened and what caused this?

**Comment by donn** [comment]
Hello Liu- not really sure, RemoteDisconnected means something may be up with your connection to GitHub. It could be that if you're sharing your IP with a whole bunch of people, GitHub is throttling connections. Mind you, this isn't as simple as loading a GitHub webpage, this is a relatively sustained 300 MB download.

To solve this problem, I would have to somehow make the download more resilient and/or enable people to download the `.tar.xz` themselves and just have volare import it. 

For now, you can try `volare build -j$(nproc)` instead of `volare enable`, which will build the PDK from sources.

**Comment by yihuajack** [comment]
Thank you donn. It is true that my connection to GitHub was still problematic and very unstable. Now I changed to a completely "normal" network of educational network, and it works.
