### ISSUE TITLE
Error when attempting to install volare module using pip

### ISSUE THREAD

**Issue by kareefardi** [efabless/volare#52]
```
Processing /home/karim/work/volare
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/karim/work/volare/setup.py", line 4, in <module>
          from volare import __version__
        File "/home/karim/work/volare/volare/__init__.py", line 14, in <module>
          from .manage import VersionNotFound, enable
        File "/home/karim/work/volare/volare/manage.py", line 18, in <module>
          import requests
      ModuleNotFoundError: No module named 'requests'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Steps to reproduce:
```
rm -rf venv
python3 -m venv ./venv 
./venv/bin/pip3 install . 
```

**Comment by donn** [comment]
Fixed in #54
